erDiagram
    movie ||--o{ session : scheduled_as
    hall ||--o{ session : hosts
    session ||--o{ ticket : includes
    client ||--o{ ticket : buys

    client {
        uuid id PK
        string *full_name
        string *email
        float money
    }
    movie {
        uuid id PK
        string *title
        string *genre
        int *duration_minutes
        int age_rating
    }
    hall {
        uuid id PK
        string *name
        int *capacity
        boolean has_3d
    }
    session {
        uuid id PK
        uuid movie_id FK
        uuid hall_id FK
        datetime *start_time
        string format
    }
    ticket {
        uuid id PK
        uuid session_id FK
        uuid client_id FK
        int *seat_number
        float *price
        boolean is_paid
    }
