erDiagram
    client {
        uuid id PK
        uuid cinema_id FK
        float *money
        string genre_preferences
        boolean interest_to_buy
    }
    booking_website {
        uuid id PK
        uuid client_id FK
        uuid cinema_id FK
        boolean *convenient_interface
        boolean *fast_website_work
        boolean attractive_design
    }
    payment_system {
        uuid id PK
        uuid client_id FK
        uuid cinema_id FK
        uuid booking_website_id FK
        boolean *card
        boolean *cash_at_desk
        string *payment_confirmation_system
        string *transaction_security
    }
    cinema {
        uuid id PK
        string *quality
        int *seats_amount
        float *prices
        string genres_spectrum
        boolean availability
        boolean student_discount
    }

    client ||--o| booking_website : browses
    cinema ||--o| booking_website : owns
    booking_website o|--|{ payment_system : integrates
    client ||--|{ payment_system : uses
    cinema ||--|{ payment_system : supports
    client ||--|| cinema : interacts