flowchart LR
    %% Актори
    User([Користувач])
    Client([Клієнт])
    PaySys[[Платіжна система]]
    VerSys[[Сервіс верифікації Дія/ЄДЕБО]]

    %% Узагальнення акторів
    User -- "|> " --- Client

    %% Прецеденти
    UC1(Купити квиток)
    UC2(Авторизуватися)
    UC3(Оплатити замовлення)
    UC4(Застосувати студентську знижку)
    UC5(Скасувати платіж)
    UC6(Переглянути документацію)
    UC7(Повернути квиток)

    %% Взаємодія акторів із системою
    Client --- UC1
    Client --- UC6
    Client --- UC7
    UC3 --- PaySys
    UC4 --- VerSys

    %% Залежності Include та Extend
    UC1 -. "<< include >>" .-> UC2
    UC1 -. "<< include >>" .-> UC3
    UC4 -. "<< extend >>" .-> UC1
    UC5 -. "<< extend >>" .-> UC3